### ISSUE TITLE
Does not work in our build

### ISSUE THREAD

**Issue by Paradox75831004** [Inoyuuuuu/lcMod_FastClimbing#1] opened 2024-02-17 01:22 UTC
Maybe some kind of mod is interfering, I think it's AC, but it's not accurate. Help me figure out if I want to add your mod...

Our build code is 018db4a8-5344-A370-9cde-c95901fe70ca

**Comment by Inoyuuuuu** [comment] 2024-02-17 01:56
Haven't used the Thunderstore mod manager before, and it is sadly not loading any mods with your code atm. Advanced company alone works fine for me, BUT **they both mess with the climbing speed**. So there's a good chance they're interfering somehow. I will look deeper into this tomorrow. Until then, try to update AC to the latest version or increasing the climbing speed in my mod's configs, so the change in speed gets more noticeable when sprinting.

**Comment by Inoyuuuuu** [comment] 2024-02-17 13:02
Can you send me a list of your installed mods and their versions? I don't think AC itself is the problem.

**Comment by Inoyuuuuu** [comment] 2024-02-18 19:51
Hi, since I'm missing the necessary informations for reproducing the bug, I will close this for now.
To my understanding, AC uses Transpiler to edit the general climbing speed, my mod is using Postfix patching. To my understanding my patch should be executed after the transpiler has edited the original code and therefore should be fine. That's probably why AC and my mod without any other mods work fine for me.
If you still have this issue, feel free to open another issue tho.

**Closed** 2024-02-18 19:51 UTC
